<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ghousia Traders Report Print Preview</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333333;
            line-height: 1.5;
            padding: 40px;
        }
        .header {
            border-bottom: 2px solid #351b0d;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .title {
            font-size: 24px;
            font-weight: bold;
            color: #351b0d;
            margin: 0 0 10px 0;
        }
        .meta-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
            font-size: 14px;
            color: #666666;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin-bottom: 40px;
        }
        .stat-card {
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            padding: 15px;
            text-align: center;
        }
        .stat-title {
            font-size: 12px;
            text-transform: uppercase;
            color: #888888;
            margin-bottom: 5px;
            font-weight: bold;
        }
        .stat-value {
            font-size: 20px;
            font-weight: bold;
            color: #351b0d;
        }
        .footer {
            margin-top: 50px;
            border-top: 1px solid #e0e0e0;
            padding-top: 20px;
            font-size: 12px;
            text-align: center;
            color: #888888;
        }
        @media print {
            body {
                padding: 0;
            }
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px; text-align: right;">
        <button onclick="window.print()" style="padding: 8px 16px; background-color: #351b0d; color: white; border: none; border-radius: 4px; cursor: pointer; font-weight: bold;">
            Print / Save to PDF
        </button>
    </div>

    <div class="header">
        <h1 class="title">Ghousia Traders Store Performance Report</h1>
        <div class="meta-grid">
            <div><strong>Period:</strong> {{ $startDate->format('M d, Y') }} - {{ $endDate->format('M d, Y') }}</div>
            <div><strong>Channel:</strong> {{ ucfirst($channel) }}</div>
            <div><strong>Payment Method:</strong> {{ ucfirst($paymentMethod) }}</div>
            <div><strong>Generated At:</strong> {{ now()->format('Y-m-d H:i:s') }}</div>
        </div>
    </div>

    <h2 style="color: #351b0d; font-size: 18px; margin-bottom: 15px;">Executive Summary</h2>
    <div class="stats-grid">
        <div class="stat-card">
            <div class="stat-title">Total Revenue</div>
            <div class="stat-value">PKR {{ number_format($stats['revenue']) }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-title">Total Orders</div>
            <div class="stat-value">{{ number_format($stats['orders']) }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-title">Total Customers</div>
            <div class="stat-value">{{ number_format($stats['customers']) }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-title">Average Order Value</div>
            <div class="stat-value">PKR {{ number_format($stats['aov']) }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-title">Refunds</div>
            <div class="stat-value">PKR {{ number_format($stats['refunds']) }}</div>
        </div>
    </div>

    <div class="footer">
        © {{ date('Y') }} Ghousia Traders. Generated by Administrator.
    </div>

    <script>
        window.addEventListener('DOMContentLoaded', () => {
            setTimeout(() => {
                window.print();
            }, 500);
        });
    </script>
</body>
</html>
